insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 8, '艾丽西亚公园1', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1001, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 8, '艾丽西亚公园2', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 2, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1002, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 8, '艾丽西亚公园3', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 1, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1003, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 12, '艾丽西亚公园4', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1004, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 12, '艾丽西亚公园5', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 4, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1005, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 12, '艾丽西亚公园6', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 5, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1007, 0, now(), now());

/*
insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 1, '艾丽西亚公园7', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1010, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 2, '艾丽西亚公园8', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 2, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1014, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 3, '艾丽西亚公园9', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 5, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1026, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 9, '艾丽西亚公园10', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1028, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 10, '艾丽西亚公园11', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1040, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 11, '艾丽西亚公园12', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1037, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 14, '艾丽西亚公园13', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 2, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1142, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 14, '艾丽西亚公园14', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 5, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1088, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 14, '艾丽西亚公园15', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1201, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 14, '艾丽西亚公园16', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1010, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 14, '艾丽西亚公园17', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1003, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 15, '艾丽西亚公园18', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 2, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1006, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 15, '艾丽西亚公园19', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 5, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1000, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 15, '艾丽西亚公园20', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1003, 0, now(), now());

insert into house (user_id, city_id, name, type, layout_area, price_desc, price_level, position, decoration_state, property, project_intro_brief, project_intro, phone_num, image_urls, is_on_sale, is_rental, view_count, status, create_time, update_time) values ( 1, 15, '艾丽西亚公园21', 1, '2居室公寓83.44㎡ ∕ 联排别墅2居室100.60㎡', '305000欧元起 / 396000欧元起', 3, '帕福斯最便利位置', '精装修', '永久产权', '项目简介项目简介项目简介项目简介项目简介项目简介', '艾丽西亚公园可算是处于帕福斯最便利的位置。它坐落于安静、弥漫着平静和休闲气息的城市中。并且，交通非常方便。她不仅能够把您从城市的车水马龙中逃离出来而且还能让您在您愿意的时候回到其中。
艾丽西亚公园是融合了豪华酒店优势的私人居住度假胜地，它提供的不只是一个家，更是一种生活方式。方便的地理位置让便利设施、景点以及休闲体验就在您家门口。充满休闲度气息的氛围让您孩子可以更加安全和自由地嬉戏。在地中海休闲居所，您只需放松地享受生活，其他的一切有我们为您安排。', '400 627 5955', './house/1.jpg;./house/2.jpg;./house/3.jpg;./house/4.jpg', 1, 0, 1000, 0, now(), now());
*/
