DROP TABLE IF EXISTS `house`;
CREATE TABLE `house` (
	house_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
	country_id INT UNSIGNED NOT NULL,
	city_id INT UNSIGNED NOT NULL,
	name VARCHAR(300) NOT NULL,
	type TINYINT NOT NULL,	-- WUYELEIXING(GONGYU, BIESHU)
	layout_area VARCHAR(300) NOT NULL, -- HUXINGMIANJI
	price_desc VARCHAR(300) NOT NULL,
	price_rmb INT UNSIGNED NOT NULL,
	position VARCHAR(300) NOT NULL,
	decoration_status VARCHAR(120) NOT NULL,
	property VARCHAR(120) NOT NULL,
	project_intro_brief VARCHAR(300) NOT NULL,
	project_intro VARCHAR(3000) NOT NULL,
	phone_num VARCHAR(20) NOT NULL,
	image_urls VARCHAR(1000) NOT NULL,
	is_sale TINYINT NOT NULL DEFAULT 1,
	status TINYINT NOT NULL DEFAULT 0,
	create_time DATETIME NOT NULL,
	update_time DATETIME NOT NULL,
	PRIMARY KEY(house_id),
	INDEX(country_id),
	INDEX(city_id),
	INDEX(name),
	INDEX(type),
	INDEX(price_rmb)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
